// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCijakSHlBwN2V1-rEwp5HDrHxPKXinRTQ',
    appId: '1:1048626144176:web:f140cce7ec317d705dec75',
    messagingSenderId: '1048626144176',
    projectId: 'fir-udemy-memo-app',
    authDomain: 'fir-udemy-memo-app.firebaseapp.com',
    storageBucket: 'fir-udemy-memo-app.firebasestorage.app',
    measurementId: 'G-4R8Z96VR88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO6cT0-5eIe1xiarFTBd4aT3_3QxgiDAE',
    appId: '1:1048626144176:android:930ffc836a46b8255dec75',
    messagingSenderId: '1048626144176',
    projectId: 'fir-udemy-memo-app',
    storageBucket: 'fir-udemy-memo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsfOfiVdzsVqS4SFGYPHGUCEutztWJuLk',
    appId: '1:1048626144176:ios:b58550d24fa3b9485dec75',
    messagingSenderId: '1048626144176',
    projectId: 'fir-udemy-memo-app',
    storageBucket: 'fir-udemy-memo-app.firebasestorage.app',
    iosBundleId: 'com.example.udemyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsfOfiVdzsVqS4SFGYPHGUCEutztWJuLk',
    appId: '1:1048626144176:ios:b58550d24fa3b9485dec75',
    messagingSenderId: '1048626144176',
    projectId: 'fir-udemy-memo-app',
    storageBucket: 'fir-udemy-memo-app.firebasestorage.app',
    iosBundleId: 'com.example.udemyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCijakSHlBwN2V1-rEwp5HDrHxPKXinRTQ',
    appId: '1:1048626144176:web:72285a55f312c5405dec75',
    messagingSenderId: '1048626144176',
    projectId: 'fir-udemy-memo-app',
    authDomain: 'fir-udemy-memo-app.firebaseapp.com',
    storageBucket: 'fir-udemy-memo-app.firebasestorage.app',
    measurementId: 'G-5WB5B4BED1',
  );

}